name: tfsec
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: 'Terraform init'
        id: init
        run: terraform init 
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
       # with:
         # soft_fail: true
         # working_directory: ./terraform
